name: diy-layout-creator
version: '4.1.0'
summary: A simple to use, free vector-based software for designing circuit layouts and schematics
description: |
  DIY Layout Creator (DIYLC in short) is a freeware drawing tool developed with help of the large online community of DIY electronics enthusiasts. It incorporates many ideas that came from people using older versions of the application. The goal is to provide a simple interface and enough power to let the user draw schematics, board/chassis layouts and guitar wiring diagrams quickly and without a steep learning curve. Also, it is buitd around a flexible open source framework that may be used to draw pretty much anything. 
  
base: core18

grade: stable
confinement: devmode

apps:
  diylc:
    extensions:
      - gnome-3-28
    command: diylc.sh
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs: [home]

parts:
  diylc:
    plugin: dump
    source: diylc-swing/build/jar/

  java:
    plugin: nil
    stage-packages:
    - openjdk-8-jre
    - openjdk-8-demo
